class Input:
    def __init__(self, array):
        self.time = array[1]
        self.demands = array[2]
        self.solar = array[3]
        self.nuclear = array[4]
        self.wind = array[5]
        self.hydro = array[6]
        self.gas = array[7]
        self.biofeul = array[8]
        self.now = array[9]
        self.h0 = array[10]
        self.h1 = array[11]
        self.h2 = array[12]
        self.h3 = array[13]
        self.h4 = array[14]
        self.solar_coef = array[15]
        self.wind_coef = array[16]
        self.hydro_coef = array[17]
        self.neighbor_power = array[18]
        self.neighbor_price = array[19]
        self.last_week = [array[20], array[21], array[22], array[23], array[24], array[25]]
